name: mobile_ultra_spacing
description: >-
  A comprehensive Flutter package for managing responsive spacing, breakpoint detection, 
  and optical adjustments across all screen sizes.

version: 0.1.2
homepage: https://khaled.ee/open-source/mobile_ultra_spacing
repository: https://github.com/KhaledSMQ/mobile_ultra_spacing.git
issue_tracker: https://github.com/KhaledSMQ/mobile_ultra_spacing/issues
documentation: https://pub.dev/packages/mobile_ultra_spacing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0